### ISSUE TITLE
Why the de-listing?

### ISSUE THREAD

**Issue by nielsenko** [BjoernPetersen/sane_uuid#36]
As someone who disagree with the internal representation of the uuid package I always found the sane_uuid package to be preferable.

I was recently made aware that it has been de-listed on pub dev. Any reason why?

**Comment by BjoernPetersen** [comment]
Honestly, I just didn't find much time to work on this package in the last years, and didn't feel like it's really ready for prime time. It's been a while, but I think there's a bug somewhere in the UUIDv1 or UUIDv5 generation that I never got around to fixing. So I thought it would be best to unlist it until I find the time some day.

I wasn't aware that anyone actually uses this package, I'm glad I'm not the only one who thinks that the uuid package's authors made some questionable design choices 😅. To be clear, I don't intend to take the package down or completely abandon it.

**Comment by nielsenko** [comment]
Thanks for the update. I would be prepared to help out, if you are interested?

**Comment by BjoernPetersen** [comment]
I'll try to take some time on Friday to refresh my own memory about the current state of the codebase and document what I think is still missing (or broken). Maybe I can identify some clear-cut tasks, then I'll gladly accept your help.

**Comment by BjoernPetersen** [comment]
Update: I did take a look on Friday and began restructuring the tests. I also cursed myself for not documenting what exactly was wrong with the UUID generation. Contrary to the comment I left in the Dart docs, I believe the buggy generator might actually the one for UUIDv1.

Next step for me is to add a test suite for that generator soon-ish, but I didn't get to it yet, since I had to re-read the RFC first to make sense of it.

I'll probably continue investigation on the 16th.

**Comment by BjoernPetersen** [comment]
Sorry about the delay, let's say life got in the way. I've added a bunch of tests and was able to verify that the behavior of the v1 and v3 generators matches that of the Python standard library's uuid package.

The package has been re-listed and you can use version 1.0.1 now.

**Comment by BjoernPetersen** [comment]
Also, to make it explicit here: I consider the package stable now, and will strictly adhere to semantic versioning from version 1.0.0 on.
